server:
    port: 8083
jwt:
  secretKey: securesecuresecuresecuresecuresecuresecure
  tokenPrefix: Bearer

spring:
    application:
        name: api-gateway

eureka:
    client:
        service-url:
            defaultZone: http://eureka-server:8761/eureka
        fetch-registry: true
        register-with-eureka: true